version: '3.8'
services:
    server:
        container_name: server
        build:
            context: ./server
            dockerfile: Dockerfile
        volumes:
            - /app/node_modules
            - ./server/config:/app/config
            - ./server/src:/app/src
            - ./server/test:/app/test
        ports:
            - "8000:8000"
    frontend:
        container_name: frontend
        environment:
            PORT: 8080
        build:
            context: ./frontend
            dockerfile: Dockerfile
        volumes:
            - /app/node_modules
            - ./frontend/src:/app/src
            - ./frontend/public:/app/public
        ports:
            - "8080:8080"