DROP TABLE "apartment_images";
DROP TABLE "apartments";

CREATE TABLE "apartments" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "link" varchar(255) NOT NULL,
  "title" text NOT NULL,
  "location" varchar(255) NOT NULL,
  "price" varchar(100) NOT NULL
);

CREATE TABLE "apartment_images" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "apartment_id" integer NOT NULL,
  "link" text NOT NULL
);

ALTER TABLE "apartment_images" ADD FOREIGN KEY ("apartment_id") REFERENCES "apartments" ("id");
